name: Run build on dev branch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * 0'

jobs:
  build:
    name: Build the Unity project
    uses: PlayEveryWare/workflow-build-unity/.github/workflows/build-pc.yml@v1
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      ref: 'development'
      binary-name: 'EOSPluginForUnity'
      google-folder-id: '1tihwPMaTOcesARsO023WYtZhdcT7z0DY'
      container-cpu-count: 30